<?php

include_once 'lib.php';
include_once 'syntaxes.php';

top();
?>
   <h1>CanyonProfiler</h1>
   <h2>Syntaxes description - Description des syntaxes</h2>
   <p>The following tables are showing the list of syntax items you can use to description your favorite canyon profile.<br/>
   Les tableaux ci-dessous présentent la liste des symboles utilisables pour décrire votre coupe de canyon.</p>
   <p>These lists are automatically generated by the code, so they are always up to date.<br/>
   Ces listes sont générées d'après le code, et sont donc constamment à jour.</p>


<ul>
<li>V1 : "Simple syntax" : Done - "Syntaxe simplifiée" : Achevée</li>
<li>V2 : "Classical syntax" : Done - "Syntaxe classique" : Achevée</li>
<li>V3 : "Advanced syntax" : Not written yet, stay tuned... - "Syntaxe avancée" : Pas encore codée, ça arrive...</li>
</ul>
<?php
// Pour chaque syntax
foreach($syntaxes as $syntaxName => $syntax) {
	echo '

	<table cellpadding="1" cellspacing="0" border="1">';
	echo '
		<tr>
			<th colspan="2">';
	echo $syntaxName;	
	echo '</th>
		</tr>';

	// Pour chaque item
	foreach($syntax as $item => $aliases) {
		echo '
		<tr>
			<td>' . $item . '</td>';
		echo '
			<td>
				<table cellpadding="1" cellspacing="0" border="0">';
		foreach($aliases as $symbol => $symbolDesc) {
			echo '
					<tr>
						<td>' . $symbol . ' : </td><td>' . $symbolDesc . '</td>
					</tr>';
		}
		echo '
				</table>
			</td>
		<tr>';
	}

	echo '
	</table>
	<br />';
} 
?>

   <h2>Options description - Description des options</h2>
   <p>The following table is showing the list of options you can use to enhance your favorite canyon profile.<br/>
   Le tableau ci-dessous présente la liste des options utilisables pour améliorer votre coupe de canyon.</p>

<?php
global $allowedOptions;
echo '

<table cellpadding="1" cellspacing="0" border="1">
	<tr>
		<th>Name</th>
		<th>Type</th>
		<th>Description</th>
		<th>Min value</th>
		<th>Max value</th>
	</tr>
';

// Pour chaque option
foreach($allowedOptions as $optionName => $optionProperties) {
	echo '
	<tr>
		<td>' . $optionName . '</td><td>' . $optionProperties[0] . '</td><td>' . $optionProperties[1] . '</td><td>' . $optionProperties[2] . '</td><td>' . $optionProperties[3] . '</td>';
	echo '
	</tr>';
} 
echo '
</table>';
?>

<?php
bottom();
?>
